<?php

/**
 * BasePicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $auction_id
 * @property string $file
 * @property boolean $is_default
 * @property integer $position
 * @property Auction $Auction
 * 
 * @method integer getAuctionId()  Returns the current record's "auction_id" value
 * @method string  getFile()       Returns the current record's "file" value
 * @method boolean getIsDefault()  Returns the current record's "is_default" value
 * @method integer getPosition()   Returns the current record's "position" value
 * @method Auction getAuction()    Returns the current record's "Auction" value
 * @method Picture setAuctionId()  Sets the current record's "auction_id" value
 * @method Picture setFile()       Sets the current record's "file" value
 * @method Picture setIsDefault()  Sets the current record's "is_default" value
 * @method Picture setPosition()   Sets the current record's "position" value
 * @method Picture setAuction()    Sets the current record's "Auction" value
 * 
 * @package    aukcje
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picture');
        $this->hasColumn('auction_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Auction', array(
             'local' => 'auction_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}