<?php

/**
 * BaseAuction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $sex
 * @property string $breeder
 * @property string $movie
 * @property clob $description
 * @property integer $price
 * @property integer $price_max
 * @property timestamp $expired_at
 * @property timestamp $start_date
 * @property boolean $is_end
 * @property boolean $is_active
 * @property Doctrine_Collection $AuctionHistory
 * @property Doctrine_Collection $Pictures
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getSex()            Returns the current record's "sex" value
 * @method string              getBreeder()        Returns the current record's "breeder" value
 * @method string              getMovie()          Returns the current record's "movie" value
 * @method clob                getDescription()    Returns the current record's "description" value
 * @method integer             getPrice()          Returns the current record's "price" value
 * @method integer             getPriceMax()       Returns the current record's "price_max" value
 * @method timestamp           getExpiredAt()      Returns the current record's "expired_at" value
 * @method timestamp           getStartDate()      Returns the current record's "start_date" value
 * @method boolean             getIsEnd()          Returns the current record's "is_end" value
 * @method boolean             getIsActive()       Returns the current record's "is_active" value
 * @method Doctrine_Collection getAuctionHistory() Returns the current record's "AuctionHistory" collection
 * @method Doctrine_Collection getPictures()       Returns the current record's "Pictures" collection
 * @method Auction             setName()           Sets the current record's "name" value
 * @method Auction             setSex()            Sets the current record's "sex" value
 * @method Auction             setBreeder()        Sets the current record's "breeder" value
 * @method Auction             setMovie()          Sets the current record's "movie" value
 * @method Auction             setDescription()    Sets the current record's "description" value
 * @method Auction             setPrice()          Sets the current record's "price" value
 * @method Auction             setPriceMax()       Sets the current record's "price_max" value
 * @method Auction             setExpiredAt()      Sets the current record's "expired_at" value
 * @method Auction             setStartDate()      Sets the current record's "start_date" value
 * @method Auction             setIsEnd()          Sets the current record's "is_end" value
 * @method Auction             setIsActive()       Sets the current record's "is_active" value
 * @method Auction             setAuctionHistory() Sets the current record's "AuctionHistory" collection
 * @method Auction             setPictures()       Sets the current record's "Pictures" collection
 * 
 * @package    aukcje
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auction');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('breeder', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('movie', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 50,
             ));
        $this->hasColumn('price_max', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 50,
             ));
        $this->hasColumn('expired_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'format' => 'Y-m-d H:i:s',
             'notnull' => true,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'format' => 'Y-m-d H:i:s',
             'notnull' => true,
             ));
        $this->hasColumn('is_end', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AuctionHistory', array(
             'local' => 'id',
             'foreign' => 'auction_id'));

        $this->hasMany('Picture as Pictures', array(
             'local' => 'id',
             'foreign' => 'auction_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             'indexName' => 'auction_slug',
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}