<?php

/**
 * AuctionHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuctionHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuctionHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuctionHistory');
    }
}