<?php

/**
 * AuctionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuctionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuctionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Auction');
    }

    public function findAuctionsByIds($ids, $toArray = false)
    {
        $q = Doctrine_Query::create()
            ->from('Auction a')
            ->leftJoin('a.Translation t')
            ->leftJoin('a.AuctionHistory h')
            ->leftJoin('h.Profile p')
            //->leftJoin('p.sfGuardUser u')
            ->whereIn('a.id ', $ids)
        ;

        $return = array();

        if($toArray)
        {
            $tmp =  $q->execute();     
            foreach($tmp as $one)
            {
                $return[$one->getPrimaryKey()] = $one;
            }
        }
        else
        {
            $return = $q->execute();
        }

        return $return;            
    }

    public function getAllAuctionQuery()
    {
     	$q = Doctrine_Query::create()
    		->from('Auction a')
            ->leftJoin('a.Translation t')
            ->leftJoin('a.AuctionHistory h')
            ->leftJoin('h.Profile p')
    		->addWhere('a.expired_at >?', date('Y-m-d H:i:s', time()))
            ->addWhere('a.start_date <=?', date('Y-m-d H:i:s', time()))            
            ->addWhere('a.is_active =?', true)
    		->orderBy('a.expired_at asc');

    	return $q;
    }

    public function getArchiveQuery()
    {
        $q = Doctrine_Query::create()
            ->from('Auction a')
            ->leftJoin('a.Translation t')
            ->leftJoin('a.AuctionHistory h')
            ->leftJoin('h.Profile p')         
            ->addWhere('a.is_end =?', true)
            ->orderBy('a.expired_at desc');

        return $q;
    }

    public function getLastAuctions($limit = 10)
    {
        $q = $this->getAllAuctionQuery();
        $q->limit($limit);
        return $q->execute();
    }

    public function getLastLicitationAuctions($limit = 10)
    {        
        $q = Doctrine_Query::create()
            ->from('AuctionHistory h');
            // ->leftJoin('h.Auction a')
            // ->addWhere('a.expired_at >?', date('Y-m-d H:i:s', time()))
            // ->addWhere('a.start_date <=?', date('Y-m-d H:i:s', time()))            
            // ->addWhere('a.is_active =?', true);

        // $q = $this->getAllAuctionQuery();
        // $q->leftJoin('a.AuctionHistory h');        
         $q->addwhere('h.profile_id is not null');        
         $q->limit($limit);
         $q->groupBy('h.auction_id');
         $q->orderBy('max(h.created_at) desc');

        return $q->execute();
    }

    public function getAuctionsToEnd()
    {
        $q = Doctrine_Query::create()
            ->from('Auction a')
            ->addWhere('a.expired_at <?', date('Y-m-d H:i:s', time()))
            ->addWhere('a.is_end =?', false)
            ->addWhere('a.is_active =?', true);
        return $q->execute();
    }

    public function getAuctionsEnded($interval = 24)
    {
        $q = Doctrine_Query::create()
            ->from('Auction a')
            ->addWhere('a.expired_at >=?', date('Y-m-d H:00:00', time() + ($interval * 60 * 60)))
            ->addWhere('a.expired_at <=?', date('Y-m-d H:59:59', time() + ($interval * 60 * 60)))
            ->addWhere('a.is_end =?', false)
            ->addWhere('a.is_active =?', true);
        return $q->execute();
    }
}
