<?php

/**
 * PictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Picture');
    }

    public function setForceOrderByAuctionId($auction_id)
    {
    	$auction = AuctionTable::getInstance()->find($auction_id);
    	if($auction)
    	{
    		$pictures = $auction->getOrderedPictures();
    		$i = 1;
	  		foreach($pictures as $picture)
	  		{
	  			$picture->setPosition($i++);
	  			$picture->save();
	  		}
    	}
    }

    public function getNextPictureByAuctionId($auction_id)
    {
    	
    	$q = Doctrine_Query::create()
    		->select('position')
			->from('Picture')
			->addWhere('auction_id = ?', $auction_id)
			->orderBy('position desc')
			->limit(1)
		;

		$position = $q->fetchArray();
		return (isset($position[0]['position'])) ? ++$position[0]['position'] : 1;
    }

    public function getByPositionAndAuctionId($position, $auction_id)
    {
    	$q = Doctrine_Query::create()
			->from('Picture')
			->where('auction_id = ?', $auction_id)
			->andWhere('position =?', $position)
		;

		return $q->fetchOne();
    }
}