<?php

/**
 * SalePictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalePictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalePictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalePicture');
    }

    public function setForceOrderBySaleId($sale_id)
    {
    	$sale = SaleTable::getInstance()->find($sale_id);
    	if($sale)
    	{
    		$pictures = $sale->getOrderedPictures();
    		$i = 1;
	  		foreach($pictures as $picture)
	  		{
	  			$picture->setPosition($i++);
	  			$picture->save();
	  		}
    	}
    }

    public function getNextPictureBySaleId($sale_id)
    {
    	
    	$q = Doctrine_Query::create()
    		->select('position')
			->from('SalePicture')
			->addWhere('sale_id = ?', $sale_id)
			->orderBy('position desc')
			->limit(1)
		;

		$position = $q->fetchArray();
		return (isset($position[0]['position'])) ? ++$position[0]['position'] : 1;
    }

    public function getByPositionAndSaleId($position, $sale_id)
    {
    	$q = Doctrine_Query::create()
			->from('SalePicture')
			->where('sale_id = ?', $sale_id)
			->andWhere('position =?', $position)
		;

		return $q->fetchOne();
    }    
}