<?php

/**
 * Sale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aukcje
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sale extends BaseSale
{
	public function getDefaultPicture()
	{
		$q = Doctrine_Query::create()
			->from('SalePicture')
			->where('sale_id =?', $this->getPrimaryKey())
			->andWhere('is_default =?', true);
		return $q->fetchOne();
	}

	public function getPicturesWithoutDefault()
	{
		$q = Doctrine_Query::create()
			->from('SalePicture')
			->where('sale_id =?', $this->getPrimaryKey())
			->andWhere('is_default =?', false)
			->orderBy('position asc');
		return $q->execute();	
	}

	private $eur = false;

	public function getPricesByCurrencies($curr = 'PLN')
	{
		if( ! $this->eur)
		{
			$this->eur = AuctionConfigTable::getInstance()->findOneByName('EUR')->getValue();
		}

		switch($curr)
		{
			case 'PLN' : $rate = $this->eur; break;
			default : $rate = 1;
		}
		
		$tmp = round($this->getPrice() * $rate, 2);
		$tmp = explode('.', $tmp);
		if(strlen($tmp[1]) == 1)
		{
			$tmp[1] .= '0';
		}
		return $tmp[0].'.'.$tmp[1];
	}

	public function getOrderedPictures()
	{
		$pictures = $this->getPictures();
		$new = array();
		foreach($pictures as $picture)
		{
			$new[$picture->getPosition()] = $picture;
		}
		ksort($new);
		return $new;
	}
}
