<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aukcje
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{

	public function delete(	Doctrine_Connection $conn = null)
	{
		if($this->getUsername() != 'admin')
		{
			$profile = $this->getProfile();
			$profile->setIsDeleted(true);
			$profile->save();
			$this->setIsActive(false);
			$this->save();	


			$histories = $profile->getAuctionHistory();
			foreach($histories as $history)
			{
				$auction = $history->getAuction();
				if($history->getIsWinner() && ! $auction->getIsEnd())
				{

					$this->deleteHistoryProfile($history, $profile);

					
					$winner = $auction->getWinnerForce();
					if($winner)
					{
						$winner->setIsWinner(true);
						$winner->save();

						$auction->setPrice($winner->getPriceActual());
						$auction->setPriceMax($winner->getPriceMax());
						
					}
					else
					{
						$auction->setPrice(50);
						$auction->setPriceMax(50);
					}
					
					$auction->save();
				}
			}

		}
		

		return true;
	}

	private function deleteHistoryProfile(AuctionHistory $history, Profile $profile)
	{
		$auction = $history->getAuction();
		$history->delete();

		$histories = $auction->getAllHistory();
		foreach($histories as $history)
		{
			if($history->getProfile()->getPrimaryKey() == $profile->getPrimaryKey())
			{
				$history->delete();
			}
			else
			{
				break;
			}
		}

	}

}
