generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sale
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sale
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css: nothing

    config:
      actions: ~
      fields:  
        name:    {label: Nazwa}
        description: {label: Opis}
        is_active: {label: Aktywny}
        price: {label: Cena}
        created_at: {label: "Data dodania"}
        mother: { label: "Matka" }
        father: { label: "Ojciec" }
        breeder: { label: "Hodowca" }
        owner:    { label: "Właściciel" }
        movie:  { label: "Film" }
      list:    
        title: "Lista przedmiotów do sprzedaży"
        display: [=id, =name, _price, is_active, created_at] 
      filter:  ~
      form:    ~
      edit:    
        title: "Edytuj przedmiot do sprzedaży"
      new:     
        title: "Dodaj nowy przedmiot do sprzedaży"
