<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Isactive extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('auction', 'is_active', 'boolean', '1', array(
             'notnull' => '1',
             'default' => '1'
      ));
    }

    public function down()
    {
    	$this->removeColumn('auction', 'is_active');
    }
}