<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('picture', 'position', 'integer', '8', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('picture', 'position');
    }
}