<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('sale_picture', 'sale_picture_sale_id_sale_id', array(
             'name' => 'sale_picture_sale_id_sale_id',
             'local' => 'sale_id',
             'foreign' => 'id',
             'foreignTable' => 'sale',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sale_translation', 'sale_translation_id_sale_id', array(
             'name' => 'sale_translation_id_sale_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'sale',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('sale_picture', 'sale_picture_sale_id', array(
             'fields' => 
             array(
              0 => 'sale_id',
             ),
             ));
        $this->addIndex('sale_translation', 'sale_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('sale_picture', 'sale_picture_sale_id_sale_id');
        $this->dropForeignKey('sale_translation', 'sale_translation_id_sale_id');
        $this->removeIndex('sale_picture', 'sale_picture_sale_id', array(
             'fields' => 
             array(
              0 => 'sale_id',
             ),
             ));
        $this->removeIndex('sale_translation', 'sale_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}